using SRF.Network.Knx.IpRouting;

namespace SRF.Network.Knx;

/// <summary>
/// Configuration options for <see cref="Connection.KnxIpRoutingBus"/>, including bus rate limiting.
/// </summary>
public class KnxIpRoutingOptions
{
    /// <summary>The default configuration section name.</summary>
    public const string DefaultConfigSectionName = "Knx:IpRouting";

    /// <summary>
    /// KNX TP physical layer bit rate in bits per second.
    /// The standard KNX TP bit rate is 9600 bit/s.
    /// Default: <c>9600</c>. Set to <c>0</c> to disable rate limiting entirely.
    /// </summary>
    public int BusBitRate { get; set; } = 9600;

    /// <summary>
    /// Average number of bits per telegram, including physical layer overhead.
    /// Used to compute <see cref="MinTelegramInterval"/> for reference.
    /// A typical KNX group telegram with a small payload requires approximately 134–200 bits.
    /// Default: <c>200</c>.
    /// </summary>
    public int AverageTelegramBits { get; set; } = 200;

    /// <summary>
    /// Number of independent KNX TP lines. Increases the effective throughput proportionally.
    /// Default: <c>1</c>.
    /// </summary>
    public int BusLineCount { get; set; } = 1;

    /// <summary>
    /// Number of bits per byte on the KNX TP UART physical layer.
    /// KNX TP uses 8-E-1 framing: 1 start bit + 8 data bits + 1 parity bit + 1 stop bit = 11 bits/byte.
    /// Default: <c>11</c>.
    /// </summary>
    public int BitsPerByte { get; set; } = 11;

    /// <summary>
    /// Fixed number of overhead bits added per telegram on the KNX TP physical layer,
    /// independent of payload size (preamble, ACK slot, inter-frame gap, etc.).
    /// Default: <c>20</c>.
    /// </summary>
    public int PhysicalOverheadBitsPerTelegram { get; set; } = 20;

    /// <summary>
    /// Token-bucket capacity in bits. The rate limiter accumulates up to this many bits of
    /// "credit" when the bus is idle, allowing short bursts before enforcing the sustained rate.
    /// Default: <c>1000</c> ≈ 5 × <see cref="AverageTelegramBits"/>.
    /// </summary>
    public int MaxBurstBits { get; set; } = 1000;

    /// <summary>
    /// Bus load fraction (0–1) above which the rate limiter enters high-load mode.
    /// In high-load mode only pre-accumulated burst credit may be spent; no new credit is
    /// generated by waiting. When the burst pool is exhausted the limiter transitions to cooldown.
    /// Default: <c>0.5</c> (50 %).
    /// </summary>
    public double MaxContinuousBusLoad { get; set; } = 0.5;

    /// <summary>
    /// Duration of the cooldown period entered when the burst pool is exhausted under high load.
    /// During cooldown, sends are spaced to not exceed <see cref="CooldownMaxBusLoad"/> of bus capacity.
    /// Default: <c>1 second</c>.
    /// </summary>
    public TimeSpan CooldownDuration { get; set; } = TimeSpan.FromSeconds(1);

    /// <summary>
    /// Maximum bus load fraction (0–1) allowed during cooldown.
    /// Sends are spaced so that the used bus bandwidth never exceeds
    /// <c>BusBitRate x BusLineCount x CooldownMaxBusLoad</c>.
    /// Set to <c>0</c> to pause sending entirely until the cooldown expires.
    /// Default: <c>0.2</c> (20 %).
    /// </summary>
    public double CooldownMaxBusLoad { get; set; } = 0.2;

    // ---- Computed properties ----

    /// <summary>
    /// Minimum interval between consecutive bus events, computed from the physical bus parameters.
    /// <para>Formula: <c>AverageTelegramBits / (BusBitRate x BusLineCount)</c></para>
    /// <para>With defaults: ~20.83 ms. Returns <see cref="TimeSpan.Zero"/> when any input is <= 0.</para>
    /// </summary>
    public TimeSpan MinTelegramInterval =>
        AverageTelegramBits <= 0 || BusBitRate <= 0 || BusLineCount <= 0
            ? TimeSpan.Zero
            : TimeSpan.FromSeconds(AverageTelegramBits / (double)(BusBitRate * BusLineCount));

    /// <summary>
    /// Duration of the sliding window used to measure bus load, derived from the token-bucket
    /// capacity and the bus bit rate.
    /// <para>Formula: <c>MaxBurstBits / (BusBitRate x BusLineCount)</c></para>
    /// <para>Returns <see cref="TimeSpan.Zero"/> when rate limiting is disabled.</para>
    /// </summary>
    public TimeSpan LoadWindowDuration =>
        MaxBurstBits <= 0 || BusBitRate <= 0 || BusLineCount <= 0
            ? TimeSpan.Zero
            : TimeSpan.FromSeconds(MaxBurstBits / (double)(BusBitRate * BusLineCount));

    /// <summary>
    /// Computes the number of KNX TP wire bits consumed by a telegram given its UDP payload size.
    /// The 6-byte KNX/IP header is subtracted to obtain the cEMI byte count, which is then encoded
    /// using the UART <see cref="BitsPerByte"/> factor plus <see cref="PhysicalOverheadBitsPerTelegram"/>.
    /// <para>Formula: <c>max(0, udpPayloadBytes - 6) x BitsPerByte + PhysicalOverheadBitsPerTelegram</c></para>
    /// </summary>
    /// <param name="udpPayloadBytes">Total UDP payload length in bytes (KNX/IP header + cEMI).</param>
    /// <returns>Estimated KNX TP wire bit count for rate-limiting purposes.</returns>
    public int ComputeTelegramBits(int udpPayloadBytes) =>
        Math.Max(0, udpPayloadBytes - KnxIpHeader.KnxIpHeaderLength) * BitsPerByte
        + PhysicalOverheadBitsPerTelegram;
}
